### Data Labeling, Merge Tables, Add Columns, Clean Text
Twitter OM; Insight Project- Michele Waters

In [144]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
import sqlite3
import datetime
import re
import string
import spacy
from spacy.lang.en.stop_words import STOP_WORDS
from spacy.lang.en import English
import nltk
import ast
from sklearn.preprocessing import LabelEncoder
import urllib

In [33]:
conn=sqlite3.connect('twitter_data_2019_2020.db')
cursor= conn.cursor()

In [12]:
#Create function to query SQL data
def query_data(sql_statement):
    df=pd.read_sql(sql_statement, conn)
    #cursor.execute(sql_statement)
    return df.to_dict('records')

In [41]:
users = [
         "barackobama",
         "michelleobama",
         "hillaryclinton",
         "speakerpelosi",
         "kamalaharris",
         "ambassadorrice",
         "repadamschiff",
         "joebiden",
         "berniesanders",
         "nycmayor",
         "who",
         "comey",
         "rodrosenstein",
         "cillizzacnn",
         "ac360",
         "donlemon",
         "brianstelter",
         "vanjones68",
         "foxnews",
         "breitbartnews",
         "nra",
         "maggieNYT",
         "bariweiss",
         #"washingtonpost",
         "maddow",
         "joenbc",
         "morningmika",
         "billoreilly",
         "seanhannity",
         "tuckercarlson",
         "ingrahamangle",
         "billmaher",
         "joerogan",
         "justinamash",
         "sarahpalinusa",
         "govchristie",
         "rudygiuliani",
         "piersmorgan",
         "mittromney",
         "senatorcollins",
         "lisamurkowski",
         "senatorloeffler",
         "nikkihaley",
         "jerryfalwelljr",
         "scottwalker",
         "tedcruz",
         "repmattgaetz",
         "randpaul",
         "realdonaldtrump",
         "mcuban",
         "kanyewest",
         "kimkardashian",
         "kyliejenner",
         "chrissyteigen",
         "justinbieber",
         "taylorswift13",
         "arianagrande",
         "selenagomez",
         "katyperry",
         "mileycyrus",
         "ddlovato",
         "shakira",
         "britneyspears",
         "jtimberlake",
         "beyonce",
         "rihanna",
         "tigerwoods",
         "snoopdogg",
         "50cent",
         "cthagod",
         "kevinhart4real",
         "chrisbrown",
         "oprah",
         "droz",
         "drdrew",
         "drphil",
         "paula_deen",
         "therealroseanne",
         "loganpaul",
         "jakepaul",
         "shanedawson",
         "oliviajadee",
         "vanessahudgens",
         "leamichele",
         "tip",
         "lancearmstrong",
         "nike",
         "nfl",
         "nba",
         "wellsfargo",
         "equifax",
         "equinox",
         #"papajohns",
         "gary_kelly",
         "jeffbezos",
         "billgates",
         "tim_cook",
         "satyanadella",
         "alexisohanian",
         "bchesky",
         "realmikelindell",
         "elonmusk",
         "crossfitceo",
         "drewbrees",
         "kaepernick7",
         "cristiano",
         "fedex",
         "twitter",
         "facebook",
         "reddit",
         "youtube",
         "natesilver538",
        ]

In [47]:
#Function to label user categories (i.e. government:1, news:2, entertainment/athletes:3, industry:4)
def label_user_category(users):
    user_cat_list=[]
    for user in users:
        user_cat=input(f'Enter label 1-4 for {user} (i.e. government:1, news:2, entertainment/athletes:3, industry:4): ')
        user_cat_list.append({'user_name': user, 'category': user_cat})
        user_cat_df=pd.DataFrame(user_cat_list)
    return user_cat_df

In [49]:
##Label users by category 
# user_cat_df=label_user_category(users)

Enter label 1-4 for barackobama (i.e. government:1, news:2, entertainment/athletes:3, industry:4): 1
Enter label 1-4 for michelleobama (i.e. government:1, news:2, entertainment/athletes:3, industry:4): 1
Enter label 1-4 for hillaryclinton (i.e. government:1, news:2, entertainment/athletes:3, industry:4): 1
Enter label 1-4 for speakerpelosi (i.e. government:1, news:2, entertainment/athletes:3, industry:4): 1
Enter label 1-4 for kamalaharris (i.e. government:1, news:2, entertainment/athletes:3, industry:4): 1
Enter label 1-4 for ambassadorrice (i.e. government:1, news:2, entertainment/athletes:3, industry:4): 1
Enter label 1-4 for repadamschiff (i.e. government:1, news:2, entertainment/athletes:3, industry:4): 1
Enter label 1-4 for joebiden (i.e. government:1, news:2, entertainment/athletes:3, industry:4): 1
Enter label 1-4 for berniesanders (i.e. government:1, news:2, entertainment/athletes:3, industry:4): 1
Enter label 1-4 for nycmayor (i.e. government:1, news:2, entertainment/athletes:3, industry:4): 1
Enter label 1-4 for who (i.e. government:1, news:2, entertainment/athletes:3, industry:4): 1
Enter label 1-4 for comey (i.e. government:1, news:2, entertainment/athletes:3, industry:4): 1
Enter label 1-4 for rodrosenstein (i.e. government:1, news:2, entertainment/athletes:3, industry:4): 1
Enter label 1-4 for cillizzacnn (i.e. government:1, news:2, entertainment/athletes:3, industry:4): 2
Enter label 1-4 for ac360 (i.e. government:1, news:2, entertainment/athletes:3, industry:4): 2
Enter label 1-4 for donlemon (i.e. government:1, news:2, entertainment/athletes:3, industry:4): 2
Enter label 1-4 for brianstelter (i.e. government:1, news:2, entertainment/athletes:3, industry:4): 2
Enter label 1-4 for vanjones68 (i.e. government:1, news:2, entertainment/athletes:3, industry:4): 2
Enter label 1-4 for foxnews (i.e. government:1, news:2, entertainment/athletes:3, industry:4): 2
Enter label 1-4 for breitbartnews (i.e. government:1, news:2, entertainment/athletes:3, industry:4): 2
Enter label 1-4 for nra (i.e. government:1, news:2, entertainment/athletes:3, industry:4): 2
Enter label 1-4 for maggieNYT (i.e. government:1, news:2, entertainment/athletes:3, industry:4): 2
Enter label 1-4 for bariweiss (i.e. government:1, news:2, entertainment/athletes:3, industry:4): 2
Enter label 1-4 for maddow (i.e. government:1, news:2, entertainment/athletes:3, industry:4): 2
Enter label 1-4 for joenbc (i.e. government:1, news:2, entertainment/athletes:3, industry:4): 2
Enter label 1-4 for morningmika (i.e. government:1, news:2, entertainment/athletes:3, industry:4): 2
Enter label 1-4 for billoreilly (i.e. government:1, news:2, entertainment/athletes:3, industry:4): 2
Enter label 1-4 for seanhannity (i.e. government:1, news:2, entertainment/athletes:3, industry:4): 2
Enter label 1-4 for tuckercarlson (i.e. government:1, news:2, entertainment/athletes:3, industry:4): 2
Enter label 1-4 for ingrahamangle (i.e. government:1, news:2, entertainment/athletes:3, industry:4): 2
Enter label 1-4 for billmaher (i.e. government:1, news:2, entertainment/athletes:3, industry:4): 2
Enter label 1-4 for joerogan (i.e. government:1, news:2, entertainment/athletes:3, industry:4): 2
Enter label 1-4 for justinamash (i.e. government:1, news:2, entertainment/athletes:3, industry:4): 1
Enter label 1-4 for sarahpalinusa (i.e. government:1, news:2, entertainment/athletes:3, industry:4): 1
Enter label 1-4 for govchristie (i.e. government:1, news:2, entertainment/athletes:3, industry:4): 1
Enter label 1-4 for rudygiuliani (i.e. government:1, news:2, entertainment/athletes:3, industry:4): 1
Enter label 1-4 for piersmorgan (i.e. government:1, news:2, entertainment/athletes:3, industry:4): 2
Enter label 1-4 for mittromney (i.e. government:1, news:2, entertainment/athletes:3, industry:4): 1
Enter label 1-4 for senatorcollins (i.e. government:1, news:2, entertainment/athletes:3, industry:4): 1
Enter label 1-4 for lisamurkowski (i.e. government:1, news:2, entertainment/athletes:3, industry:4): 1
Enter label 1-4 for senatorloeffler (i.e. government:1, news:2, entertainment/athletes:3, industry:4): 1
Enter label 1-4 for nikkihaley (i.e. government:1, news:2, entertainment/athletes:3, industry:4): 1
Enter label 1-4 for jerryfalwelljr (i.e. government:1, news:2, entertainment/athletes:3, industry:4): 1
Enter label 1-4 for scottwalker (i.e. government:1, news:2, entertainment/athletes:3, industry:4): 1
Enter label 1-4 for tedcruz (i.e. government:1, news:2, entertainment/athletes:3, industry:4): 1
Enter label 1-4 for repmattgaetz (i.e. government:1, news:2, entertainment/athletes:3, industry:4): 1
Enter label 1-4 for randpaul (i.e. government:1, news:2, entertainment/athletes:3, industry:4): 1
Enter label 1-4 for realdonaldtrump (i.e. government:1, news:2, entertainment/athletes:3, industry:4): 1
Enter label 1-4 for mcuban (i.e. government:1, news:2, entertainment/athletes:3, industry:4): 4
Enter label 1-4 for kanyewest (i.e. government:1, news:2, entertainment/athletes:3, industry:4): 3
Enter label 1-4 for kimkardashian (i.e. government:1, news:2, entertainment/athletes:3, industry:4): 3
Enter label 1-4 for kyliejenner (i.e. government:1, news:2, entertainment/athletes:3, industry:4): 3
Enter label 1-4 for chrissyteigen (i.e. government:1, news:2, entertainment/athletes:3, industry:4): 3
Enter label 1-4 for justinbieber (i.e. government:1, news:2, entertainment/athletes:3, industry:4): 3
Enter label 1-4 for taylorswift13 (i.e. government:1, news:2, entertainment/athletes:3, industry:4): 3
Enter label 1-4 for arianagrande (i.e. government:1, news:2, entertainment/athletes:3, industry:4): 3
Enter label 1-4 for selenagomez (i.e. government:1, news:2, entertainment/athletes:3, industry:4): 3
Enter label 1-4 for katyperry (i.e. government:1, news:2, entertainment/athletes:3, industry:4): 3
Enter label 1-4 for mileycyrus (i.e. government:1, news:2, entertainment/athletes:3, industry:4): 3
Enter label 1-4 for ddlovato (i.e. government:1, news:2, entertainment/athletes:3, industry:4): 3
Enter label 1-4 for shakira (i.e. government:1, news:2, entertainment/athletes:3, industry:4): 3
Enter label 1-4 for britneyspears (i.e. government:1, news:2, entertainment/athletes:3, industry:4): 3
Enter label 1-4 for jtimberlake (i.e. government:1, news:2, entertainment/athletes:3, industry:4): 3
Enter label 1-4 for beyonce (i.e. government:1, news:2, entertainment/athletes:3, industry:4): 3
Enter label 1-4 for rihanna (i.e. government:1, news:2, entertainment/athletes:3, industry:4): 3
Enter label 1-4 for tigerwoods (i.e. government:1, news:2, entertainment/athletes:3, industry:4): 3
Enter label 1-4 for snoopdogg (i.e. government:1, news:2, entertainment/athletes:3, industry:4): 3
Enter label 1-4 for 50cent (i.e. government:1, news:2, entertainment/athletes:3, industry:4): 3
Enter label 1-4 for cthagod (i.e. government:1, news:2, entertainment/athletes:3, industry:4): 3
Enter label 1-4 for kevinhart4real (i.e. government:1, news:2, entertainment/athletes:3, industry:4): 3
Enter label 1-4 for chrisbrown (i.e. government:1, news:2, entertainment/athletes:3, industry:4): 3
Enter label 1-4 for oprah (i.e. government:1, news:2, entertainment/athletes:3, industry:4): 3
Enter label 1-4 for droz (i.e. government:1, news:2, entertainment/athletes:3, industry:4): 3
Enter label 1-4 for drdrew (i.e. government:1, news:2, entertainment/athletes:3, industry:4): 3
Enter label 1-4 for drphil (i.e. government:1, news:2, entertainment/athletes:3, industry:4): 3
Enter label 1-4 for paula_deen (i.e. government:1, news:2, entertainment/athletes:3, industry:4): 3
Enter label 1-4 for therealroseanne (i.e. government:1, news:2, entertainment/athletes:3, industry:4): 3
Enter label 1-4 for loganpaul (i.e. government:1, news:2, entertainment/athletes:3, industry:4): 3
Enter label 1-4 for jakepaul (i.e. government:1, news:2, entertainment/athletes:3, industry:4): 3
Enter label 1-4 for shanedawson (i.e. government:1, news:2, entertainment/athletes:3, industry:4): 3
Enter label 1-4 for oliviajadee (i.e. government:1, news:2, entertainment/athletes:3, industry:4): 3
Enter label 1-4 for vanessahudgens (i.e. government:1, news:2, entertainment/athletes:3, industry:4): 3

Enter label 1-4 for leamichele (i.e. government:1, news:2, entertainment/athletes:3, industry:4): 3
Enter label 1-4 for tip (i.e. government:1, news:2, entertainment/athletes:3, industry:4): 3
Enter label 1-4 for lancearmstrong (i.e. government:1, news:2, entertainment/athletes:3, industry:4): 3
Enter label 1-4 for nike (i.e. government:1, news:2, entertainment/athletes:3, industry:4): 4
Enter label 1-4 for nfl (i.e. government:1, news:2, entertainment/athletes:3, industry:4): 4
Enter label 1-4 for nba (i.e. government:1, news:2, entertainment/athletes:3, industry:4): 4
Enter label 1-4 for wellsfargo (i.e. government:1, news:2, entertainment/athletes:3, industry:4): 4
Enter label 1-4 for equifax (i.e. government:1, news:2, entertainment/athletes:3, industry:4): 4
Enter label 1-4 for equinox (i.e. government:1, news:2, entertainment/athletes:3, industry:4): 4
Enter label 1-4 for gary_kelly (i.e. government:1, news:2, entertainment/athletes:3, industry:4): 4
Enter label 1-4 for jeffbezos (i.e. government:1, news:2, entertainment/athletes:3, industry:4): 4
Enter label 1-4 for billgates (i.e. government:1, news:2, entertainment/athletes:3, industry:4): 4
Enter label 1-4 for tim_cook (i.e. government:1, news:2, entertainment/athletes:3, industry:4): 4
Enter label 1-4 for satyanadella (i.e. government:1, news:2, entertainment/athletes:3, industry:4): 4
Enter label 1-4 for alexisohanian (i.e. government:1, news:2, entertainment/athletes:3, industry:4): 4
Enter label 1-4 for bchesky (i.e. government:1, news:2, entertainment/athletes:3, industry:4): 4
Enter label 1-4 for realmikelindell (i.e. government:1, news:2, entertainment/athletes:3, industry:4): 4
Enter label 1-4 for elonmusk (i.e. government:1, news:2, entertainment/athletes:3, industry:4): 4
Enter label 1-4 for crossfitceo (i.e. government:1, news:2, entertainment/athletes:3, industry:4): 4
Enter label 1-4 for drewbrees (i.e. government:1, news:2, entertainment/athletes:3, industry:4): 3
Enter label 1-4 for kaepernick7 (i.e. government:1, news:2, entertainment/athletes:3, industry:4): 3
Enter label 1-4 for cristiano (i.e. government:1, news:2, entertainment/athletes:3, industry:4): 3
Enter label 1-4 for fedex (i.e. government:1, news:2, entertainment/athletes:3, industry:4): 4
Enter label 1-4 for twitter (i.e. government:1, news:2, entertainment/athletes:3, industry:4): 4
Enter label 1-4 for facebook (i.e. government:1, news:2, entertainment/athletes:3, industry:4): 4
Enter label 1-4 for reddit (i.e. government:1, news:2, entertainment/athletes:3, industry:4): 4
Enter label 1-4 for youtube (i.e. government:1, news:2, entertainment/athletes:3, industry:4): 4
Enter label 1-4 for natesilver538 (i.e. government:1, news:2, entertainment/athletes:3, industry:4): 2

In [50]:
user_cat_df

          user_name category
0       barackobama        1
1     michelleobama        1
2    hillaryclinton        1
3     speakerpelosi        1
4      kamalaharris        1
..              ...      ...
105         twitter        4
106        facebook        4
107          reddit        4
108         youtube        4
109   natesilver538        2

[110 rows x 2 columns]

In [51]:
user_cat_df.to_sql('user_categories', conn, index_label='id', if_exists='replace')

In [34]:
end_date="2019-01-01"
now = datetime.datetime.now()
day=int(now.day)
month=int(now.month)
year=int(now.year)
user_info = "twitter_user_account_info_%i_%i_%i" % (now.month, now.day, now.year)

In [35]:
user_df=pd.DataFrame(query_data(f'''SELECT * FROM {user_info}''')).drop(columns='id')

In [36]:
user_df.head()

,account_id,location,screen_name,name,description,url,created_at,verified,followers_count,friends_count,listed_count,favourites_count,statuses_count
0,813286,"Washington, DC",barackobama,Barack Obama,"Dad, husband, President, citizen.",https://t.co/93Y27HEnnX,Mon Mar 05 22:08:25 +0000 2007,1,119658056,604838,220889,5,15843
1,409486555,"Washington, DC",michelleobama,Michelle Obama,Girl from the South Side and former First Lady...,https://t.co/0UVvR5L6vm,Thu Nov 10 20:13:01 +0000 2011,1,15769786,18,23865,175,1348
2,1339835893,"New York, NY",hillaryclinton,Hillary Clinton,"2016 Democratic Nominee, SecState, Senator, ha...",https://t.co/99DVW9q1yt,Tue Apr 09 18:04:35 +0000 2013,1,28133366,840,39987,1118,11696
3,15764644,San Francisco,speakerpelosi,Nancy Pelosi,"Speaker of the House, focused on strengthening...",https://t.co/jztVqrP3x5,Thu Aug 07 15:35:02 +0000 2008,1,4808527,362,18804,11,10459
4,30354991,California,kamalaharris,Kamala Harris,"U.S. Senator. Wife, Momala, Auntie. Still figh...",http://t.co/IbL01p7pYJ,Sat Apr 11 00:42:07 +0000 2009,1,3800744,734,13366,339,13727

In [54]:
#Merge tweet info, user account info, and user category info
df=pd.DataFrame(query_data(f'''SELECT * FROM merged_twitter_{end_date[:4]}_present
                                JOIN {user_info} ON {user_info}.screen_name = merged_twitter_{end_date[:4]}_present.username
                                JOIN user_categories ON user_categories.user_name= {user_info}.screen_name''')).drop(columns='id')

/Users/michelewaters/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:5: UserWarning: DataFrame columns are not unique, some columns will be omitted.
  """

In [55]:
df.head()

,username,text,url_attached,hashtags,reply_to,date,formatted_date,to,link_to_tweet,tweet_id,...,url,created_at,verified,followers_count,friends_count,listed_count,favourites_count,statuses_count,user_name,category
0,barackobama,As has always been true at key moments in hist...,https://www.obama.org/updates/president-obama-...,[],None,2020-06-07 23:25:01+00:00,Sun Jun 07 23:25:01 +0000 2020,None,https://twitter.com/BarackObama/status/1269772...,1269772382509596677,...,https://t.co/93Y27HEnnX,Mon Mar 05 22:08:25 +0000 2007,1,119658056,604838,220889,5,15843,barackobama,1
1,barackobama,We’ve seen the power that our voices have when...,https://twitter.com/ObamaFoundation/status/126...,[],ObamaFoundation,2020-06-06 00:37:08+00:00,Sat Jun 06 00:37:08 +0000 2020,ObamaFoundation,https://twitter.com/BarackObama/status/1269065...,1269065755179524096,...,https://t.co/93Y27HEnnX,Mon Mar 05 22:08:25 +0000 2007,1,119658056,604838,220889,5,15843,barackobama,1
2,barackobama,"On National Gun Violence Awareness Day, we #We...",None,['#WearOrange'],None,2020-06-05 16:21:00+00:00,Fri Jun 05 16:21:00 +0000 2020,None,https://twitter.com/BarackObama/status/1268940...,1268940899616243715,...,https://t.co/93Y27HEnnX,Mon Mar 05 22:08:25 +0000 2007,1,119658056,604838,220889,5,15843,barackobama,1
3,barackobama,"Third, every city in this country should be a ...",http://obama.org/mbka/about-mbk-communities,[],None,2020-06-04 23:15:58+00:00,Thu Jun 04 23:15:58 +0000 2020,None,https://twitter.com/BarackObama/status/1268682...,1268682939799425024,...,https://t.co/93Y27HEnnX,Mon Mar 05 22:08:25 +0000 2007,1,119658056,604838,220889,5,15843,barackobama,1
4,barackobama,"Second, every mayor should review their use of...",http://obama.org/mayor-pledge,[],None,2020-06-04 23:15:58+00:00,Thu Jun 04 23:15:58 +0000 2020,None,https://twitter.com/BarackObama/status/1268682...,1268682938251710464,...,https://t.co/93Y27HEnnX,Mon Mar 05 22:08:25 +0000 2007,1,119658056,604838,220889,5,15843,barackobama,1

In [56]:
df.tail()

,username,text,url_attached,hashtags,reply_to,date,formatted_date,to,link_to_tweet,tweet_id,...,url,created_at,verified,followers_count,friends_count,listed_count,favourites_count,statuses_count,user_name,category
249740,natesilver538,Worth remembering that Romney got a larger sha...,None,[],None,2019-01-02 16:42:16+00:00,Wed Jan 02 16:42:16 +0000 2019,None,https://twitter.com/NateSilver538/status/10805...,1080504559712165889,...,http://t.co/wNpFg2xg4f,Wed Aug 27 20:56:45 +0000 2008,1,3326049,1299,30802,983,30162,natesilver538,2
249741,natesilver538,Too many hot takes trying to find the strategi...,None,[],None,2019-01-02 02:55:44+00:00,Wed Jan 02 02:55:44 +0000 2019,None,https://twitter.com/NateSilver538/status/10802...,1080296556660613121,...,http://t.co/wNpFg2xg4f,Wed Aug 27 20:56:45 +0000 2008,1,3326049,1299,30802,983,30162,natesilver538,2
249742,natesilver538,Have been in LA for New Year's and I sorta fee...,None,[],None,2019-01-02 02:21:32+00:00,Wed Jan 02 02:21:32 +0000 2019,None,https://twitter.com/NateSilver538/status/10802...,1080287950909263872,...,http://t.co/wNpFg2xg4f,Wed Aug 27 20:56:45 +0000 2008,1,3326049,1299,30802,983,30162,natesilver538,2
249743,natesilver538,This is quite the ratio. Coming around to the ...,None,[],None,2019-01-02 01:21:59+00:00,Wed Jan 02 01:21:59 +0000 2019,None,https://twitter.com/NateSilver538/status/10802...,1080272962068967430,...,http://t.co/wNpFg2xg4f,Wed Aug 27 20:56:45 +0000 2008,1,3326049,1299,30802,983,30162,natesilver538,2
249744,natesilver538,"I think this held up reasonably well. 2018, wi...",https://twitter.com/NateSilver538/status/94765...,[],NateSilver538,2019-01-01 01:53:01+00:00,Tue Jan 01 01:53:01 +0000 2019,NateSilver538,https://twitter.com/NateSilver538/status/10799...,1079918384815296513,...,http://t.co/wNpFg2xg4f,Wed Aug 27 20:56:45 +0000 2008,1,3326049,1299,30802,983,30162,natesilver538,2

In [58]:
df.columns

Index(['username', 'text', 'url_attached', 'hashtags', 'reply_to', 'date',
       'formatted_date', 'to', 'link_to_tweet', 'tweet_id', 'retweets',
       'favorites', 'reply_count', 'author_id', 'ratio_comment_like',
       'ratio_comment_retweet', 'log_ratio', 'ratio_richter_likes',
       'ratio_richter_retweets', 'got_ratioed', 'got_richter_ratioed',
       'd_richter_like_ratio', 'd_richter_retweet_ratio', 'account_id',
       'location', 'screen_name', 'name', 'description', 'url', 'created_at',
       'verified', 'followers_count', 'friends_count', 'listed_count',
       'favourites_count', 'statuses_count', 'user_name', 'category'],
      dtype='object')

In [59]:
#Drop duplicate columns
df=df.drop(columns=['screen_name', 'user_name'])

In [60]:
#Add date columns from original date column
df['doy']=df.date.apply(lambda x: pd.to_datetime(x).timetuple().tm_yday)
df['year']=df.date.apply(lambda x: pd.to_datetime(x).year)
df['hour']=df.date.apply(lambda x: pd.to_datetime(x).hour)
df['minute']=df.date.apply(lambda x: pd.to_datetime(x).minute)
df['second']=df.date.apply(lambda x: pd.to_datetime(x).second)

### Tweet Text Cleaning

In [61]:
tweets=df

In [62]:
tweets['text'][0]

'As has always been true at key moments in history, it’s going to depend on young people to go out there and rewrite what is possible. I couldn’t be prouder of all the young people leading that change right now. Here’s my advice for the Class of 2020:'

In [69]:
#Remove contractions
contraction_list = { 
"ain’t": "am not",
"aren’t": "are not",
"can’t": "cannot",
"can’t’ve": "cannot have",
"’cause": "because",
"could’ve": "could have",
"couldn’t": "could not",
"couldn’t've": "could not have",
"didn’t": "did not",
"doesn’t": "does not",
"don’t": "do not",
"’em": "them",
"hadn’t": "had not",
"hadn’t've": "had not have",
"hasn’t": "has not",
"haven’t": "have not",
"he’d": "he would",
"he’d’ve": "he would have",
"he’ll": "he will",
"here’s": "here is",
"he’s": "he is",
"how’d": "how did",
"how’ll": "how will",
"how’s": "how is",
"i’d": "i would",
"i’ll": "i will",
"i’m": "i am",
"i’ve": "i have",
"isn’t": "is not",
"it’d": "it would",
"it’ll": "it will",
"it’s": "it is",
"let’s": "let us",
"ma’am": "madam",
"mayn’t": "may not",
"might’ve": "might have",
"mightn’t": "might not",
"must’ve": "must have",
"mustn’t": "must not",
"needn’t": "need not",
"oughtn’t": "ought not",
"shan’t": "shall not",
"sha’n’t": "shall not",
"she’d": "she would",
"she’ll": "she will",
"she’s": "she is",
"should’ve": "should have",
"shouldn’t": "should not",
"that’d": "that would",
"that’s": "that is",
"there’d": "there had",
"there’s": "there is",
"they’d": "they would",
"they’ll": "they will",
"they’re": "they are",
"they’ve": "they have",
"wasn’t": "was not",
"we’d": "we would",
"we’ll": "we will",
"we’re": "we are",
"we’ve": "we have",
"weren’t": "were not",
"what’ll": "what will",
"what’re": "what are",
"what’s": "what is",
"what’ve": "what have",
"where’d": "where did",
"where’s": "where is",
"who’ll": "who will",
"who’s": "who is",
"won’t": "will not",
"wouldn’t": "would not",
"you’d": "you would",
"you’ll": "you will",
"you’re": "you are",
"thx"   : "thanks"
}

def clean_contractions(text):
    sentence=""
    for word in text.lower().replace('"', '').split():
        if word in contraction_list.keys():
            sentence+=f" {contraction_list[word]}"
        else:
            sentence+=f" {word}"
    return sentence

In [70]:
#Clean contractions and lowercase tweets
tweets['text_processed']=tweets['text'].apply(lambda t: clean_contractions(t))

In [71]:
tweets['text_processed'][0]

' as has always been true at key moments in history, it is going to depend on young people to go out there and rewrite what is possible. i could not be prouder of all the young people leading that change right now. here is my advice for the class of 2020:'

In [74]:
#Remove punctuation
tweets['text_processed']=tweets['text_processed'].apply(lambda t: re.sub(r'[^a-zA-Z\s]', '', t.replace('.', ' ')).replace('\s+\s', ' '))

In [75]:
tweets['text_processed'][0]

' as has always been true at key moments in history it is going to depend on young people to go out there and rewrite what is possible  i could not be prouder of all the young people leading that change right now  here is my advice for the class of '

In [81]:
#Remove stopwords/Tokenize data

# Create our list of punctuation marks
punctuations = string.punctuation

# Create our list of stopwords
nlp = spacy.load('en')
stop_words = spacy.lang.en.stop_words.STOP_WORDS

# Load English tokenizer, tagger, parser, NER and word vectors
parser = English()

# Creating our tokenizer function
def spacy_tokenizer(sentence):
    # Creating our token object, which is used to create documents with linguistic annotations.
    mytokens = parser(sentence)

    # Lemmatizing each token and converting each token into lowercase
    mytokens = [ word.lemma_.lower().strip() if word.lemma_ != "-PRON-" else word.lower_ for word in mytokens ]

    # Removing stop words
    mytokens = [ word for word in mytokens if word not in stop_words and word not in punctuations ]

    # return preprocessed list of tokens
    return mytokens

In [82]:
#Remove stop words and tokenize text
token_tweet_list=[]
for t in tweets['text_processed'].to_list():
    token_tweet_list.append(spacy_tokenizer(t))

In [83]:
token_tweet_list[0]

['true',
 'key',
 'moments',
 'history',
 'going',
 'depend',
 'young',
 'people',
 'rewrite',
 'possible',
 'prouder',
 'young',
 'people',
 'leading',
 'change',
 'right',
 'advice',
 'class']

In [84]:
token_sentences=[]
for token_tweet in token_tweet_list:
    token_sentences.append(' '.join(token_tweet))

In [85]:
token_sentences[0]

'true key moments history going depend young people rewrite possible prouder young people leading change right advice class'

In [88]:
#Stem sentences

from nltk.stem.snowball import SnowballStemmer
from nltk.stem.snowball import SnowballStemmer

def stem_sentences(token_tweet_list):
    stemmer = SnowballStemmer(language='english')
    stem_token_sentences=[]
    for token_tweet in token_tweet_list:
        stem_tokens=[]
        for token in token_tweet:
            stem_tokens.append(stemmer.stem(token))
        stem_token_sentences.append(' '.join(stem_tokens))
    return stem_token_sentences

In [89]:
stem_token_sentences=stem_sentences(token_tweet_list)

In [90]:
stem_token_sentences[0]

'true key moment histori go depend young peopl rewrit possibl prouder young peopl lead chang right advic class'

Decided not to use stemming result, to keep context of whole words

In [91]:
#Lemmatize sentences

from nltk.stem import WordNetLemmatizer 
nltk.download('wordnet')

def lemmatize_sentences(token_sentences):
    lemmatizer = WordNetLemmatizer() 
    lm_sentences=[]
    for token_sentence in token_sentences:
        lm_sentence=[]
        for word in token_sentence.split():
            lm_sentence.append(lemmatizer.lemmatize(word))
        lm_sentences.append(' '.join(lm_sentence))
    return lm_sentences

[nltk_data] Downloading package wordnet to
[nltk_data]     /Users/michelewaters/nltk_data...
[nltk_data]   Package wordnet is already up-to-date!

In [92]:
lm_sentences=lemmatize_sentences(token_sentences)

In [93]:
lm_sentences[0]

'true key moment history going depend young people rewrite possible prouder young people leading change right advice class'

In [94]:
len(lm_sentences)

249745

In [105]:
#Save result to dataframe
df['cleaned_text']=lm_sentences

In [106]:
df.head()

,username,text,url_attached,hashtags,reply_to,date,formatted_date,to,link_to_tweet,tweet_id,...,favourites_count,statuses_count,category,doy,year,hour,minute,second,text_processed,cleaned_text
0,barackobama,As has always been true at key moments in hist...,https://www.obama.org/updates/president-obama-...,[],None,2020-06-07 23:25:01+00:00,Sun Jun 07 23:25:01 +0000 2020,None,https://twitter.com/BarackObama/status/1269772...,1269772382509596677,...,5,15843,1,159,2020,23,25,1,as has always been true at key moments in his...,true key moment history going depend young peo...
1,barackobama,We’ve seen the power that our voices have when...,https://twitter.com/ObamaFoundation/status/126...,[],ObamaFoundation,2020-06-06 00:37:08+00:00,Sat Jun 06 00:37:08 +0000 2020,ObamaFoundation,https://twitter.com/BarackObama/status/1269065...,1269065755179524096,...,5,15843,1,158,2020,0,37,8,we have seen the power that our voices have w...,seen power voice speak injusticebut know toll ...
2,barackobama,"On National Gun Violence Awareness Day, we #We...",None,['#WearOrange'],None,2020-06-05 16:21:00+00:00,Fri Jun 05 16:21:00 +0000 2020,None,https://twitter.com/BarackObama/status/1268940...,1268940899616243715,...,5,15843,1,157,2020,16,21,0,on national gun violence awareness day we wea...,national gun violence awareness day wearorange...
3,barackobama,"Third, every city in this country should be a ...",http://obama.org/mbka/about-mbk-communities,[],None,2020-06-04 23:15:58+00:00,Thu Jun 04 23:15:58 +0000 2020,None,https://twitter.com/BarackObama/status/1268682...,1268682939799425024,...,5,15843,1,156,2020,23,15,58,third every city in this country should be a ...,city country mbkalliance community city county...
4,barackobama,"Second, every mayor should review their use of...",http://obama.org/mayor-pledge,[],None,2020-06-04 23:15:58+00:00,Thu Jun 04 23:15:58 +0000 2020,None,https://twitter.com/BarackObama/status/1268682...,1268682938251710464,...,5,15843,1,156,2020,23,15,58,second every mayor should review their use of...,second mayor review use force policy member co...

In [108]:
df.columns

Index(['username', 'text', 'url_attached', 'hashtags', 'reply_to', 'date',
       'formatted_date', 'to', 'link_to_tweet', 'tweet_id', 'retweets',
       'favorites', 'reply_count', 'author_id', 'ratio_comment_like',
       'ratio_comment_retweet', 'log_ratio', 'ratio_richter_likes',
       'ratio_richter_retweets', 'got_ratioed', 'got_richter_ratioed',
       'd_richter_like_ratio', 'd_richter_retweet_ratio', 'account_id',
       'location', 'name', 'description', 'url', 'created_at', 'verified',
       'followers_count', 'friends_count', 'listed_count', 'favourites_count',
       'statuses_count', 'category', 'doy', 'year', 'hour', 'minute', 'second',
       'text_processed', 'cleaned_text'],
      dtype='object')

### Label Encode Hashtag and Url data

Hashtags

In [142]:
df.hashtags.unique()

array(['[]', "['#WearOrange']", "['#BlackHistoryMonth']", ...,
       "['#AxeFiles']", "['#TweetBetter', '#NeverTweet']",
       "['#horserace']"], dtype=object)

In [112]:
#Function to clean hashtags by removing '#' and lowercasing, and to count the number of hashtags/if present
def clean_num_hashtags(hash_tag_col=df.hashtags):
    clean_hashes=[]
    all_hashes=[]
    for hashes in list(hash_tag_col):
        hash_list= ast.literal_eval(hashes)
        c_hashes=[d_hash.replace("#", "").lower() for d_hash in hash_list]
        for c_hash in c_hashes:
            all_hashes.append(c_hash)
        clean_hashes.append({'hashtag_list': c_hashes, 'num_hashtags': len(c_hashes), 'hashtag_present':int(len(c_hashes)>0)})
    return pd.DataFrame(clean_hashes)

In [113]:
clean_hashes_df=clean_num_hashtags(hash_tag_col=df.hashtags)

In [115]:
clean_hashes_df.iloc[2030:2035]

                     hashtag_list  num_hashtags  hashtag_present
2030               [forthepeople]             1                1
2031         [defendourdemocracy]             1                1
2032         [defendourdemocracy]             1                1
2033                           []             0                0
2034  [protectthedream, dreamers]             2                1

In [116]:
clean_hashes_df['num_hashtags'].unique()

array([ 0,  1,  2,  3,  4,  7,  6,  5, 10,  8,  9, 11, 12, 19, 14, 16])

In [117]:
clean_hashes_df['num_hashtags'].value_counts()

0     180008
1      44812
2      18621
3       5090
4        943
5        170
6         36
7         26
8         14
9          8
10         6
19         3
12         3
11         3
16         1
14         1
Name: num_hashtags, dtype: int64

In [118]:
clean_hashes_df['num_hashtags'].value_counts('normalize')[:2].sum()

0.9001982021662095

Since 90% of tweets have no hashtag or one hashtag, use label encoding to represent first hashtag in list

In [119]:
clean_hashes_df['hashtag_list'].value_counts()[:10]

[]                                180008
[drphil]                            2897
[nbatogetherlive]                   1616
[covid19]                           1582
[nfl100]                            1107
[coronavirus, covid19]               708
[demdebate]                          706
[nbatogether]                        643
[coronavirus]                        601
[lecheminduroi, bransoncognac]       569
Name: hashtag_list, dtype: int64

In [120]:
first_hashtags=clean_hashes_df['hashtag_list'].apply(lambda x: x[0] if x!=[] else '')

In [121]:
clean_hashes_df['first_hashtag']=first_hashtags

In [122]:
clean_hashes_df.iloc[2030:2035]

,hashtag_list,num_hashtags,hashtag_present,first_hashtag
2030,[forthepeople],1,1,forthepeople
2031,[defendourdemocracy],1,1,defendourdemocracy
2032,[defendourdemocracy],1,1,defendourdemocracy
2033,[],0,0,
2034,"[protectthedream, dreamers]",2,1,protectthedream

In [130]:
#Function to use sklearn's label encoder to give individual hashtags unique values
def first_hashtag_encoder_df(clean_hashes_df):
    first_hashtags=clean_hashes_df['hashtag_list'].apply(lambda x: x[0] if x!=[] else '')
    clean_hashes_df['first_hashtag']=first_hashtags
    enc_hashtag=LabelEncoder().fit_transform(clean_hashes_df['first_hashtag'])
    clean_hashes_df['encoded_hashtag']=enc_hashtag
    return clean_hashes_df

In [131]:
clean_hashes_df=first_hashtag_encoder_df(clean_hashes_df)

In [132]:
clean_hashes_df.iloc[2030:2035]

,hashtag_list,num_hashtags,hashtag_present,first_hashtag,encoded_hashtag
2030,[forthepeople],1,1,forthepeople,2259
2031,[defendourdemocracy],1,1,defendourdemocracy,1580
2032,[defendourdemocracy],1,1,defendourdemocracy,1580
2033,[],0,0,,0
2034,"[protectthedream, dreamers]",2,1,protectthedream,5325

In [133]:
len(clean_hashes_df['first_hashtag'].unique())

7654

In [134]:
len(clean_hashes_df['encoded_hashtag'].unique())

7654

Urls

In [143]:
df.url_attached.unique()

array(['https://www.obama.org/updates/president-obama-dear-class-2020/',
       'https://twitter.com/ObamaFoundation/status/1269058266950242317',
       'None', ...,
       'https://twitter.com/GrahamDavidA/status/1080833125956112385',
       'https://twitter.com/PatrickRuffini/status/1080508522327085059',
       'https://twitter.com/NateSilver538/status/947656664160915457'],
      dtype=object)

In [149]:
df.url_attached.unique()[2]=='None'

True

In [172]:
from urllib.parse import urlparse

#Function to clean urls ang get first two/main parts of url
def clean_urls(url_col=df.url_attached):
    clean_urls=[]
    for url in list(df.url_attached):
            if url=='None':
                clean_url= ''
                url_present=0
            else:
                if url[-1]!='/':
                    url=url+'/'
                urls_parts=urlparse(url)
                if len(urls_parts.path)>0:
                    clean_url= urls_parts.netloc+' '+urls_parts.path.split("/")[1]
                else:
                    clean_url= urls_parts.netloc
                url_present=1
            clean_urls.append({'url_list': clean_url, 'url_present': url_present})
    return pd.DataFrame(clean_urls)

In [183]:
clean_urls_df=clean_urls(url_col=df.url_attached)

In [184]:
clean_urls_df.head()

                      url_list  url_present
0        www.obama.org updates            1
1  twitter.com ObamaFoundation            1
2                                         0
3               obama.org mbka            1
4       obama.org mayor-pledge            1

In [185]:
#Function to label encode url
def url_encoder_df(clean_urls_df):
    enc_url=LabelEncoder().fit_transform(clean_urls_df['url_list'])
    clean_urls_df['encoded_urls']=enc_url
    return clean_urls_df

In [186]:
clean_urls_df=url_encoder_df(clean_urls_df)

In [187]:
clean_urls_df.head()

                      url_list  url_present  encoded_urls
0        www.obama.org updates            1         60582
1  twitter.com ObamaFoundation            1         49129
2                                         0             0
3               obama.org mbka            1         14350
4       obama.org mayor-pledge            1         14349

In [188]:
len(clean_urls_df.encoded_urls.unique())

63429

In [196]:
#Merge hashtag and url data with original dataframs
df=pd.concat([df, clean_urls_df[['encoded_urls', 'url_present']], clean_hashes_df[['encoded_hashtag', 'hashtag_present','num_hashtags' ]]],axis=1)

In [197]:
df.head()

,username,text,url_attached,hashtags,reply_to,date,formatted_date,to,link_to_tweet,tweet_id,...,hour,minute,second,text_processed,cleaned_text,encoded_urls,url_present,encoded_hashtag,hashtag_present,num_hashtags
0,barackobama,As has always been true at key moments in hist...,https://www.obama.org/updates/president-obama-...,[],None,2020-06-07 23:25:01+00:00,Sun Jun 07 23:25:01 +0000 2020,None,https://twitter.com/BarackObama/status/1269772...,1269772382509596677,...,23,25,1,as has always been true at key moments in his...,true key moment history going depend young peo...,60582,1,0,0,0
1,barackobama,We’ve seen the power that our voices have when...,https://twitter.com/ObamaFoundation/status/126...,[],ObamaFoundation,2020-06-06 00:37:08+00:00,Sat Jun 06 00:37:08 +0000 2020,ObamaFoundation,https://twitter.com/BarackObama/status/1269065...,1269065755179524096,...,0,37,8,we have seen the power that our voices have w...,seen power voice speak injusticebut know toll ...,49129,1,0,0,0
2,barackobama,"On National Gun Violence Awareness Day, we #We...",None,['#WearOrange'],None,2020-06-05 16:21:00+00:00,Fri Jun 05 16:21:00 +0000 2020,None,https://twitter.com/BarackObama/status/1268940...,1268940899616243715,...,16,21,0,on national gun violence awareness day we wea...,national gun violence awareness day wearorange...,0,0,7251,1,1
3,barackobama,"Third, every city in this country should be a ...",http://obama.org/mbka/about-mbk-communities,[],None,2020-06-04 23:15:58+00:00,Thu Jun 04 23:15:58 +0000 2020,None,https://twitter.com/BarackObama/status/1268682...,1268682939799425024,...,23,15,58,third every city in this country should be a ...,city country mbkalliance community city county...,14350,1,0,0,0
4,barackobama,"Second, every mayor should review their use of...",http://obama.org/mayor-pledge,[],None,2020-06-04 23:15:58+00:00,Thu Jun 04 23:15:58 +0000 2020,None,https://twitter.com/BarackObama/status/1268682...,1268682938251710464,...,23,15,58,second every mayor should review their use of...,second mayor review use force policy member co...,14349,1,0,0,0

In [198]:
df.columns

Index(['username', 'text', 'url_attached', 'hashtags', 'reply_to', 'date',
       'formatted_date', 'to', 'link_to_tweet', 'tweet_id', 'retweets',
       'favorites', 'reply_count', 'author_id', 'ratio_comment_like',
       'ratio_comment_retweet', 'log_ratio', 'ratio_richter_likes',
       'ratio_richter_retweets', 'got_ratioed', 'got_richter_ratioed',
       'd_richter_like_ratio', 'd_richter_retweet_ratio', 'account_id',
       'location', 'name', 'description', 'url', 'created_at', 'verified',
       'followers_count', 'friends_count', 'listed_count', 'favourites_count',
       'statuses_count', 'category', 'doy', 'year', 'hour', 'minute', 'second',
       'text_processed', 'cleaned_text', 'encoded_urls', 'url_present',
       'encoded_hashtag', 'hashtag_present', 'num_hashtags'],
      dtype='object')

In [199]:
#Save dataframe to SQL database
df.to_sql(f'cleaned_merged_twitter_{end_date[:4]}', conn, index_label='id', if_exists='replace')

In [200]:
end_date[:4]

'2019'

In [201]:
test_df=pd.DataFrame(query_data('SELECT * from cleaned_merged_twitter_2019'))

In [202]:
test_df.head()

,id,username,text,url_attached,hashtags,reply_to,date,formatted_date,to,link_to_tweet,...,hour,minute,second,text_processed,cleaned_text,encoded_urls,url_present,encoded_hashtag,hashtag_present,num_hashtags
0,0,barackobama,As has always been true at key moments in hist...,https://www.obama.org/updates/president-obama-...,[],None,2020-06-07 23:25:01+00:00,Sun Jun 07 23:25:01 +0000 2020,None,https://twitter.com/BarackObama/status/1269772...,...,23,25,1,as has always been true at key moments in his...,true key moment history going depend young peo...,60582,1,0,0,0
1,1,barackobama,We’ve seen the power that our voices have when...,https://twitter.com/ObamaFoundation/status/126...,[],ObamaFoundation,2020-06-06 00:37:08+00:00,Sat Jun 06 00:37:08 +0000 2020,ObamaFoundation,https://twitter.com/BarackObama/status/1269065...,...,0,37,8,we have seen the power that our voices have w...,seen power voice speak injusticebut know toll ...,49129,1,0,0,0
2,2,barackobama,"On National Gun Violence Awareness Day, we #We...",None,['#WearOrange'],None,2020-06-05 16:21:00+00:00,Fri Jun 05 16:21:00 +0000 2020,None,https://twitter.com/BarackObama/status/1268940...,...,16,21,0,on national gun violence awareness day we wea...,national gun violence awareness day wearorange...,0,0,7251,1,1
3,3,barackobama,"Third, every city in this country should be a ...",http://obama.org/mbka/about-mbk-communities,[],None,2020-06-04 23:15:58+00:00,Thu Jun 04 23:15:58 +0000 2020,None,https://twitter.com/BarackObama/status/1268682...,...,23,15,58,third every city in this country should be a ...,city country mbkalliance community city county...,14350,1,0,0,0
4,4,barackobama,"Second, every mayor should review their use of...",http://obama.org/mayor-pledge,[],None,2020-06-04 23:15:58+00:00,Thu Jun 04 23:15:58 +0000 2020,None,https://twitter.com/BarackObama/status/1268682...,...,23,15,58,second every mayor should review their use of...,second mayor review use force policy member co...,14349,1,0,0,0

In [204]:
test_df.columns

Index(['id', 'username', 'text', 'url_attached', 'hashtags', 'reply_to',
       'date', 'formatted_date', 'to', 'link_to_tweet', 'tweet_id', 'retweets',
       'favorites', 'reply_count', 'author_id', 'ratio_comment_like',
       'ratio_comment_retweet', 'log_ratio', 'ratio_richter_likes',
       'ratio_richter_retweets', 'got_ratioed', 'got_richter_ratioed',
       'd_richter_like_ratio', 'd_richter_retweet_ratio', 'account_id',
       'location', 'name', 'description', 'url', 'created_at', 'verified',
       'followers_count', 'friends_count', 'listed_count', 'favourites_count',
       'statuses_count', 'category', 'doy', 'year', 'hour', 'minute', 'second',
       'text_processed', 'cleaned_text', 'encoded_urls', 'url_present',
       'encoded_hashtag', 'hashtag_present', 'num_hashtags'],
      dtype='object')

In [208]:
test_df[['username','cleaned_text','retweets', 'favorites', 'reply_count', 'ratio_richter_likes', 'hashtag_present']][20000:20005]

,username,cleaned_text,retweets,favorites,reply_count,ratio_richter_likes,hashtag_present
20000,nycmayor,running time protect coastal city climate chan...,53,170,89,-1.261571,0
20001,nycmayor,attack new zealand premeditated act terror ins...,57,211,73,-1.977728,0
20002,nycmayor,chelseaclinton dedicated life standing hate di...,1077,5832,1214,-4.840494,0
20003,nycmayor,writer poet soldier bricklayer irish immigrant...,23,57,19,-1.404854,1
20004,nycmayor,thinking fdny fire marshal christopher tripp z...,10,44,3,-1.281346,0